[buildPlans.IosevkaSr21Web_4h6hU]
family = "Iosevka-SR21-Web-4h6hU"
spacing = "fixed"
serifs = "sans"
noCvSs = true
exportGlyphNames = false

[buildPlans.IosevkaSr21Web_4h6hU.variants.design]
one = "base"
three = "flat-top-serifless"
four = "closed-serifless"
five = "upright-arched-serifless"
six = "closed-contour"
seven = "straight-serifless-crossbar"
eight = "crossing-asymmetric"
nine = "closed-contour"
zero = "slashed"
capital-a = "straight-serifless"
capital-c = "serifless"
capital-g = "toothless-corner-serifless-hooked"
capital-i = "serifed"
capital-j = "serifed"
capital-p = "closed-serifless"
capital-q = "crossing-baseline"
capital-r = "straight-serifless"
capital-s = "serifless"
capital-w = "straight-vertical-sides-serifless"
capital-z = "straight-serifless-with-horizontal-crossbar"
a = "double-storey-serifless"
b = "toothed-serifless"
d = "toothed-serifless"
e = "flat-crossbar"
f = "flat-hook-tailed"
g = "double-storey-open"
i = "serifed"
j = "serifed"
m = "earless-rounded-double-arch-serifless"
r = "serifless"
t = "bent-hook"
u = "toothless-rounded-serifless"
w = "straight-vertical-sides-serifless"
z = "straight-serifless-with-horizontal-crossbar"
lower-theta = "oval"
lower-pi = "tailed"
lower-psi = "serifless"
cyrl-capital-ya = "standing-serifless"
tittle = "round"
diacritic-dot = "square"
punctuation-dot = "round"
braille-dot = "square"
tilde = "low"
asterisk = "hex-low"
underscore = "above-baseline"
caret = "medium"
paren = "flat-arc"
guillemet = "straight"
number-sign = "upright"
ampersand = "upper-open"
at = "fourfold"
dollar = "interrupted"
bar = "natural-slope"
question = "corner-flat-hooked"
decorative-angle-brackets = "tall"
lig-ltgteq = "slanted"
lig-equal-chain = "without-notch"
lig-hyphen-chain = "without-notch"

  [buildPlans.IosevkaSr21Web_4h6hU.ligations]
  inherits = "dlig"

[buildPlans.IosevkaSr21Web_4h6hU.weights.Regular]
shape = 400
menu = 400
css = 400

[buildPlans.IosevkaSr21Web_4h6hU.weights.ExtraLight]
shape = 200
menu = 200
css = 200

[buildPlans.IosevkaSr21Web_4h6hU.weights.Light]
shape = 300
menu = 300
css = 300

[buildPlans.IosevkaSr21Web_4h6hU.widths.Normal]
shape = 600
menu = 5
css = "normal"

[buildPlans.IosevkaSr21Web_4h6hU.slopes.Upright]
angle = 0
shape = "upright"
menu = "upright"
css = "normal"
